// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD3UgpTUum_JYJ5FrPcxouLpSas6YIkZY',
    appId: '1:709335841416:web:ff9b7b06d5b7189ba37d3d',
    messagingSenderId: '709335841416',
    projectId: 'booking-9edb3',
    authDomain: 'booking-9edb3.firebaseapp.com',
    storageBucket: 'booking-9edb3.appspot.com',
    measurementId: 'G-47PNL8ZL3Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd3Oy24vWCtrHkN9BhHJw3UwdPluTJcvE',
    appId: '1:709335841416:android:c5d499f7c0b77ed3a37d3d',
    messagingSenderId: '709335841416',
    projectId: 'booking-9edb3',
    storageBucket: 'booking-9edb3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8GtaEuN7nUakDDuojibX2iMwtCjHI_98',
    appId: '1:709335841416:ios:3bb9b1a3462bd4aca37d3d',
    messagingSenderId: '709335841416',
    projectId: 'booking-9edb3',
    storageBucket: 'booking-9edb3.appspot.com',
    iosClientId: '709335841416-tompqh11s7qmk1v6gq5i7lms7nio1cle.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );
}
