// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpEsl7U7JxtpGBdO_-bjrrFtGQFZs22D8',
    appId: '1:441833996112:web:4d062ded3cc87996ddb655',
    messagingSenderId: '441833996112',
    projectId: 'booking-hotel-de0ca',
    authDomain: 'booking-hotel-de0ca.firebaseapp.com',
    storageBucket: 'booking-hotel-de0ca.appspot.com',
    measurementId: 'G-R02RGTDZBW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0h_Qs89UmxOIuLca9IJScrZORGcC_63M',
    appId: '1:441833996112:android:bb7dc7fe25d37b71ddb655',
    messagingSenderId: '441833996112',
    projectId: 'booking-hotel-de0ca',
    storageBucket: 'booking-hotel-de0ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVcUxi1uh0xRUy6QISWCB3Dg-GZUdruLU',
    appId: '1:441833996112:ios:05f6a97911dece21ddb655',
    messagingSenderId: '441833996112',
    projectId: 'booking-hotel-de0ca',
    storageBucket: 'booking-hotel-de0ca.appspot.com',
    iosClientId: '441833996112-7rgs3o43ka804j9c3jvlta9gdq406rj3.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );
}
